displayName=FC Boot Protector
description=Prevents accidental boots/kicks in Friends Chat
author=AbsentPlays
tags=clan, antikick, fc
version=1.0
plugins=com.fcbootprotector.FcBootProtectorPlugin
build=standard
